# must patch storage class to be default
# oc patch storageclass ibmc-file-gold-gid  -p '{"metadata": {"annotations":{"storageclass.kubernetes.io/is-default-class":"true"}}}'
# oc patch storageclass ibmc-block-gold -p '{"metadata": {"annotations":{"storageclass.kubernetes.io/is-default-class":"false"}}}'
#
# create namespace
kind: Namespace
apiVersion: v1
metadata:
  name: websphere-automation
  labels:
    name: websphere-automation
---
# create catalogsource
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-operator-catalog
  namespace: openshift-marketplace
spec:
  displayName: IBM Operator Catalog
  publisher: IBM
  sourceType: grpc
  image: icr.io/cpopen/ibm-operator-catalog:latest
  updateStrategy:
    registryPoll:
      interval: 45m
---
# add Operator Group
apiVersion: operators.coreos.com/v1alpha2
kind: OperatorGroup
metadata:
  name: ibm-websphere-automation
  namespace: websphere-automation
spec:
  targetNamespaces:
  - websphere-automation
---
# Install Operator
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: ibm-websphere-automation
  namespace: websphere-automation
spec:
  channel: v1.7
  installPlanApproval: Automatic
  name: ibm-websphere-automation
  source: ibm-operator-catalog
  sourceNamespace: openshift-marketplace

