FROM open-liberty:full-java11-openj9

USER 0
RUN apt-get update && apt-get -y upgrade
USER 1001
COPY --chown=1001:0  server-mq2amq.xml /config/server.xml
COPY --chown=1001:0  definitions.xml /config/definitions.xml
COPY --chown=1001:0  JMSMQ.war /config/apps/
COPY --chown=1001:0  wmq.jmsra.rar /config/resources/
COPY --chown=1001:0  activemq-rar-5.16.2.rar /config/resources/

