# create namespace
kind: Namespace
apiVersion: v1
metadata:
  name: open-liberty
  labels:
    name: open-liberty
---
# create operator group
apiVersion: operators.coreos.com/v1alpha2
kind: OperatorGroup
metadata:
  name: open-liberty
  namespace: open-liberty
spec:
  targetNamespaces:
  - open-liberty
---
# Install Operator
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: open-liberty
  namespace: open-liberty
spec:
  channel: beta2
  installPlanApproval: Automatic
  name: open-liberty-certified
  source: certified-operators
  sourceNamespace: openshift-marketplace
